name:unittest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/
        -name: notify
          needs: test
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: ${{ secrets.SMTP_HOST }}
            server_port: ${{ secrets.SMTP_PORT }}
            username: ${{ secrets.SMTP_USERNAME }}
            password: ${{ secrets.SMTP_PASSWORD }}
            subject: 'GitHub Actions Notification: ${{github.workflow}}'
            to: ${{ secrets.EMAIL_TO }}'
            from: ${{ secrets.EMAIL_FROM }}
            body: |
              Build job status: ${{ needs.test.result }}
              workflow: ${{ github.workflow }}
              commit: ${{ github.sha }}
              branch: ${{ github.ref }}
              url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
